
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 07 02:57:48 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 42;
  public static final int CONST = 24;
  public static final int GE = 16;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int FOLLOW = 29;
  public static final int MINUS = 23;
  public static final int RPAREN = 7;
  public static final int AND = 25;
  public static final int LT = 20;
  public static final int OR = 43;
  public static final int COMMA = 8;
  public static final int CLASS = 38;
  public static final int INC = 32;
  public static final int DIV = 22;
  public static final int PLUS = 11;
  public static final int IF = 49;
  public static final int THIS = 34;
  public static final int DOT = 21;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int PERCENT = 19;
  public static final int NUMBER = 45;
  public static final int NEQ = 40;
  public static final int IDENT = 46;
  public static final int BREAK = 30;
  public static final int VOID = 13;
  public static final int EQ = 41;
  public static final int TIMES = 28;
  public static final int FOREACH = 36;
  public static final int COLON = 15;
  public static final int ELSE = 50;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 26;
  public static final int ENUM = 27;
  public static final int READ = 31;
  public static final int CHARCONST = 48;
  public static final int RSQUARE = 39;
  public static final int WHILE = 35;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int DEC = 44;
  public static final int GT = 14;
  public static final int DO = 37;
  public static final int PRINT = 9;
}

