
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  public static final int ELSE = 17;
  public static final int IDENT = 15;
  public static final int PLUS = 11;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 12;
  public static final int SEMI = 5;
  public static final int RETURN = 10;
  public static final int IF = 16;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int PROG = 2;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int VOID = 13;
  public static final int LSQUARE = 18;
  public static final int RSQUARE = 19;
  public static final int PERCENT = 20;
  public static final int BREAK = 21;
  public static final int CLASS = 22;
  public static final int ENUM = 23;
  public static final int CONST = 24;
  public static final int WHILE = 25;
  public static final int DO = 26;
  public static final int NEW = 27;
  public static final int READ = 28;
  public static final int EXTENDS = 29;
  public static final int CONT = 30;
  public static final int THIS = 31;
  public static final int FOREACH = 32;
  public static final int MINUS = 33;
  public static final int TIMES = 34;
  public static final int DIV = 35;
  public static final int EQ = 36;
  public static final int NEQ = 37;
  public static final int GT = 38;
  public static final int GE = 39;
  public static final int LT = 40;
  public static final int LE = 41;
  public static final int AND = 42;
  public static final int OR = 43;
  public static final int INC = 44;
  public static final int DEC = 45;
  public static final int COLON = 46;
  public static final int DOT = 47;
  public static final int FOLLOW = 47;
  public static final int BOOLCONST = 48;




}

